### ISSUE TITLE
TLS 1.0

### ISSUE THREAD

**Issue by nsimeonov** [HelloFax/hellosign-dotnet-sdk#65]
Probably a lame question, but better safe than sorry.

Related to disabling TLS 1.0 on Jan 31, for a .Net MVC app using HelloSign NuGet package (0.5.5 is what I see installed currently), do we need to change anything or upgrading to latest version is enough? I see the app is targeting .net framework 4.5.2, which supports TLS 1.2

I saw recommendations to add code to app startup: https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5

**Comment by BHSPitMonkey** [comment]
Not lame at all!

My own research mirrors what you see in that StackOverflow answer, and so I'm under the impression that as long as _your application_ targets .NET Framework 4.0 or above you will be able to use that workaround (or if you target 4.5.2 and higher, I think it will try to do the right thing out of the box). I haven't been able to do much testing in this area, so I can't say whether that's 100% accurate in all cases.

We'll be releasing version 1.0.0 of this library in the coming several days, which will now target .NET Framework 4.5.2 as a minimum (or .NET Standard 2.0 as a new addition), which I hope most people are able to migrate to soon so that the TLS situation can be a bit more clear-cut.

Let us know if this works out for you, or if you hit any snags!

**Comment by nsimeonov** [comment]
One of our systems just stopped. It was compiled using .net framework 4.5.2, but we were getting errors. I quickly hacked it by adding this to Global.asax to get it back up and running.

```
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
```

This works, but feels like using a big hammer, when we should use a screwdriver...
